### ISSUE TITLE
xss

### ISSUE THREAD

**Issue by lintaba** [mkkp/invalid-voter#1]
xss sebezhetoseg az image-ben.

**Comment by nowseemee** [comment]
Mi a megoldas?

**Comment by lintaba** [comment]
duplicated by #2

**Comment by lintaba** [comment]
@nowseemee https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by Silur** [comment]
nem szabad engedni hogy bekerüljön a js contextbe bármi amit a user beír, a `%0A` karakter a kulcs úgyhogy egy sima php string sanitize meg kéne oldja.

**Comment by boti7** [comment]
ugye ha regex-el kiszedjük a spec karaktereket az elég?
`preg_replace("/[^a-z0-9]/", "", $_GET['image'])`

**Comment by Silur** [comment]
elméletileg igen, de majd letesztelem újra :)

**Comment by boti7** [comment]
kész, javítva van
